In [100]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt 
from sklearn import preprocessing


df = pd.read_csv(r"C:\Users\amr15\Desktop\AiDataNTI\insurance.csv")

print(df)

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]


In [99]:
df.isnull().sum()

time     0
cells    0
dtype: int64

In [86]:
input_df = df.drop(columns='expenses')
target_df = df['expenses']


In [87]:
from sklearn import preprocessing

columns_to_encode = ['sex', 'smoker', 'region']
encoders = {}

for column in columns_to_encode:
    encoder = preprocessing.LabelEncoder()
    input_df[column] = encoder.fit_transform(input_df[column].astype(str))
    encoders[column] = encoder

input_df.head()


age  sex   bmi  children  smoker  region
0   19    0  27.9         0       1       3
1   18    1  33.8         1       0       2
2   28    1  33.0         3       0       2
3   33    1  22.7         0       0       1
4   32    1  28.9         0       0       1

In [88]:
from sklearn.preprocessing import MinMaxScaler

column_name = "expenses"  # مش "expenses" إلا لو أنت مغيره
scaler = MinMaxScaler()

scaler.fit(df[[column_name]])
scaled_data = scaler.transform(df[[column_name]])


array([[0.25161073],
       [0.00963598],
       [0.05311519],
       ...,
       [0.00810809],
       [0.01414366],
       [0.44724875]], shape=(1338, 1))

In [89]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(input_df,scaled_data,test_size=0.2,random_state=20)

print(y_test.shape)


(268, 1)


In [90]:
from sklearn.linear_model import LinearRegression

reg=LinearRegression().fit(x_train,y_train)
reg.score(x_test, y_test)


0.7960343002915863

In [92]:
predciction_test = reg.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error


In [94]:
predciction_test = reg.predict(x_test)
print(y_test,predciction_test)

[[1.57296193e-01]
 [3.91624484e-01]
 [1.35813656e-01]
 [2.24238195e-01]
 [8.37305758e-03]
 [9.93797782e-03]
 [3.28012328e-02]
 [1.30277376e-01]
 [4.63906433e-01]
 [1.22004081e-01]
 [2.31295340e-01]
 [5.35531543e-01]
 [3.44461229e-02]
 [1.43083576e-01]
 [2.85743040e-01]
 [1.30260137e-01]
 [3.38550479e-01]
 [2.87679557e-01]
 [3.25558959e-02]
 [1.72538044e-01]
 [7.47122679e-01]
 [1.39400810e-01]
 [1.77195294e-01]
 [9.42336105e-03]
 [8.84995601e-02]
 [5.29364123e-02]
 [3.53127350e-01]
 [1.60670732e-01]
 [5.63072958e-01]
 [1.10158478e-01]
 [1.18089865e-01]
 [3.77097255e-02]
 [4.75993702e-01]
 [7.30541771e-01]
 [5.16374199e-01]
 [2.16941938e-02]
 [5.27868478e-02]
 [2.13194046e-02]
 [3.29608055e-01]
 [2.21628558e-01]
 [1.75706193e-01]
 [1.97114347e-01]
 [1.47460692e-02]
 [3.33115398e-02]
 [1.88416462e-01]
 [1.05429079e-01]
 [6.83034055e-02]
 [5.49465143e-02]
 [7.11721706e-01]
 [5.81681367e-02]
 [9.30082032e-02]
 [4.21590536e-01]
 [1.32890205e-01]
 [1.45408450e-01]
 [6.95334418e-02]
 [5.318237

In [97]:
MEAValu = mean_absolute_error(y_test,predciction_test,multioutput='uniform_average')
print('MEAVal= ', MEAValu)
MSEValu = mean_squared_error (y_test,predciction_test,multioutput='uniform_average')
print('MSEValu= ', MSEValu)
MDSEValu = median_absolute_error (y_test,predciction_test,multioutput='uniform_average')
print('MDSEValu= ', MDSEValu)


MEAVal=  0.06442242043952309
MSEValu=  0.007814568608666899
MDSEValu=  0.04135267791888149


In [102]:
df = pd.read_csv(r"C:\Users\amr15\Desktop\AiDataNTI\cells.csv")

print(df)

    time  cells
0    0.0    205
1    0.5    225
2    1.0    238
3    1.5    240
4    2.0    248
5    2.5    260
6    3.0    265
7    3.5    283
8    4.0    301
9    4.5    305
10   5.0    309


In [ ]:
from sklearn.preprocessing import MinMaxScaler

column_name = "cells"  # مش "expenses" إلا لو أنت مغيره
scaler = MinMaxScaler()

scaler.fit(df[[column_name]])
scaled_data = scaler.transform(df[[column_name]])
scaled_data


array([[0.        ],
       [0.19230769],
       [0.31730769],
       [0.33653846],
       [0.41346154],
       [0.52884615],
       [0.57692308],
       [0.75      ],
       [0.92307692],
       [0.96153846],
       [1.        ]])

In [106]:
input_df_cells = df.drop(columns='cells')


In [111]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(input_df_cells ,scaled_data,test_size=0.2,random_state=42)

print(y_test.shape)


(3, 1)


In [112]:
from sklearn.linear_model import LinearRegression

reg=LinearRegression().fit(x_train,y_train)
reg.score(x_test, y_test)


0.9819544532247534